apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  namespace: ml-platform
  labels:
    app: ml-api
spec:
  selector:
    app: ml-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer  # GKE will provision external IP
